### ISSUE TITLE
Using with logging

### ISSUE THREAD

**Issue by asyncee** [tommikaikkonen/prettyprinter#1]
Hi, very nice and beautiful package.

But how do i use it with logging?

For example, if i have a StreamLogger, should i write a custom formatter for it?

**Comment by tommikaikkonen** [comment]
I'm not very familiar with using pretty printers in a logging context, but here are my thoughts.

[`prettyprinter.pformat`](https://prettyprinter.readthedocs.io/en/latest/api_reference.html#prettyprinter.pformat) returns output as a string, which you could use for logging. This output will not be syntax highlighted. (You can output `cpprint` to a StringIO instance using the `stream` kwarg if you want a string with syntax highlighting.)

Now, if you want to have this kind of statement
```python
logger.info('Value: %s', [1, 2, 3])
```

to use PrettyPrinter to render args like `[1, 2, 3]` above, looking at the `logging` module source, you would have to override `LogRecord.getMessage()`, so that you first call `prettyprinter.pformat` on each of the args before the `logging` module casts the args to strings with `msg % args` in `LogRecord.getMessage`. It seems like you could bypass the `getMessage()` call by writing a custom formatter (see [this line](https://github.com/python/cpython/blob/3.6/Lib/logging/__init__.py#L575)), which might be easier.

Note that:
- PrettyPrinter will be slower than other printers, so if you do a lot of logging, it will affect application performance.
- Syntax highlighting is done using ANSI escape sequences. How it looks in your output will depend on where you view your logs.

**Comment by asyncee** [comment]
Great, thank you very much for detailed explanation!
