### ISSUE TITLE
numpy.float64 is printed differently from other numpy numeric types

### ISSUE THREAD

**Issue by anntzer** [tommikaikkonen/prettyprinter#36]
* PrettyPrinter version: 0.14.0
* Python version: 3.7
* Operating System: fedora linux

### Description

See below.

### What I Did

```
from prettyprinter import cpprint as pp
import numpy as np

pp(np.uint8(1))
pp(np.int8(1))
pp(np.uint16(1))
pp(np.int16(1))
pp(np.float16(1))
pp(np.uint32(1))
pp(np.int32(1))
pp(np.float32(1))
pp(np.uint64(1))
pp(np.int64(1))
pp(np.float64(1))
```
yields
```
1
1
1
1
1.0
1
1
1.0
1
1
numpy.float64(1.0)
```
i.e. numpy.float64 is the only numpy type whose printing includes the explicit type.

I'm not actually sure whether I prefer including the type in that case or not (it's a bit verbose, but could also be useful), but at least it should be consistent across numpy numeric types.

**Comment by tommikaikkonen** [comment]
I think to provide proper prettyprinting for numpy, it needs custom printers. Probably as an opt-in extra.

What's happening here is that `prettyprinter` is delegating the printing to the `__repr__` method of the numpy numeric type for all but `numpy.float64`. This is because prettyprinter registers a printer for `int` and `float` and all of their subclasses. Of the numpy numeric types, only `float64` is a subclass of float or int. If a registered pretty printer is not found in a value's class hierarchy, `prettyprinter` calls `__repr__` on it. That's why it prints out differently.

Yeah, I'm not sure either if the output should be wrapped with the class constructor or not. I would default to wrapping it, but I agree that wrapping it can significantly add verbosity if you're looking at a lot of numbers. I've never used numpy, so I don't have enough context to make a good decision there.

I'm open to accepting a PR with `numpy` prettyprinter definitions as an extra. It should be fairly easy to copy another extra file (such as the `requests` one), put in numpy definitions and write some test cases for it. Just registering those numeric classes to use `pretty_int` or `pretty_float` should work well to start off:

```python
>>> from prettyprinter.prettyprinter import pretty_int
>>> from prettyprinter import register_pretty
>>> register_pretty('numpy.uint8')(pretty_int)
>>> import numpy
>>> numpy.uint8(1)
numpy.uint8(1)
```
